import Head from 'next/head'
import React from 'react';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram, AiFillFacebook, AiFillYoutube } from 'react-icons/ai';
import{AiFillStar} from 'react-icons/ai'
import Image from 'next/image';
import virul from 'public/ReadyPlayerMe-Avatar.png';
import code from 'public/code.png';
import consulting from 'public/consulting.png';
import design from 'public/design.png';
import websample1 from 'public/websample1.png';
import websample2 from 'public/websample2.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>virul.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon"  href ="/vnlogo.png" className=' rounded-3xl' />
      </Head>

      <main className=' bg-white px-10'>
        <section className='min-h-screen'>
          <nav className=' py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl font-Mono'>develope by virul.n</h1>
            <ul className=' flex items-center'>
              <li>
                <BsFillMoonStarsFill className=' cursor-pointer text-2xl' />
              </li>
              <li>
                <a className=' bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">More</a>
              </li>
            </ul>
          </nav>
          <div className=' relative mx-auto bg-gradient-to-b from-blue-500 rounded-full w-80 h-80 mt-20'>
            <Image src={virul} alt={'virul'} />
          </div>
          <div className=' text-center p-10'>
            <h2 className=' text-5xl py-2 text-teal-600 font-Mono font-medium'> Virul Nirmala</h2>
            <h3 className=' text-2xl py-2 font-bold'>Developer and Designer.</h3>
            <p className=' text-md py-5 leading-8 text-gray-900'>
              I start to learn video editing using youtube 2018 and now I have some knowledge about video editing. I'm editing videos using kdenlive.I made some project and sell them to my friends. Also I'm designer. I do photoshop editing and GIMP editing. I can make your photos and videos look Professional and I can make Graphic arts for you.Also I'm full stack software developer.
            </p>
          </div>
          <div className=' text-5xl flex justify-center gap-10 py-3  text-gray-600 cursor-pointer'>
            <a href="https://www.facebook.com/virulnirmala/"><AiFillFacebook /></a>
            <a href="https://www.instagram.com/virul_n_w/"><AiFillInstagram /></a>
            <a href="https://twitter.com/NirmalaVirul"><AiFillTwitterCircle /></a>
            <a href="https://www.youtube.com/channel/UCWrVxJzOmiQn4MEs3oovGtg"><AiFillYoutube /></a>
            <a href="https://www.linkedin.com/in/virul-nirmala-a2b220217/"><AiFillLinkedin /></a>
          </div>

        </section>
        <section>
          <div>
            <h3 className=' font-Mono text-3xl py-1'>Services I offer</h3>
            <p className=' text-md py-2 leading-8 text-gray-600'>You can revise your project for unlimited times until you're fully satisfied.
              Cross Platform compatibility (i.e. Chrome, Safari, Edge etc.)
              Top notch User Experience.
              Social Media Integration, Google Maps, Contact Forms ,Subscription and more
              SSL Security.
              Admin Panel we build is highly responsive and easy to use.
              Industry Leading after sales service.</p>
          </div>
          <div className=' col-span-2 flex justify-center gap-4 p-10'>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 card leftcard'>
              < Image className=' m-auto' src={design} alt={'design'} width={100} height={100} />
              <h3 className=' font-lg font-bold pt-8 pb-2'>Beautiful Designs</h3>
              <p>
                Creating elegant design suited for your needs.
              </p>
              <h4 className=' py-4 text-teal-600 font-bold'> Design tools I use</h4>
              <p className=' text-gray-800 py-1 font-Mono font-bold'>Photoshop</p>
              <p className=' text-gray-800 py-1 font-Mono font-bold'>Kdenlive</p>
              <p className=' text-gray-800 py-1 font-Mono font-bold'>GIMP</p>
              <p className=' text-gray-800 py-1 font-Mono font-bold'>Blender</p>
              <p className=' text-gray-800 py-1 font-Mono font-bold'>Figma</p>
              <p className=' text-gray-800 py-1 font-Mono font-bold'>Illustrator</p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 card '>
              < Image className=' m-auto' src={code} alt={'design'} width={100} height={100} />
              <h3 className=' font-lg font-bold pt-8 pb-2'>Code</h3>
              <p>
                Creating elegant design suited for your needs.
              </p>
              <h4 className=' py-4 text-teal-600 font-bold'>The languages I'm good at</h4>
              <p className=' text-gray-800 py-1 font-Mono font-bold'>JAVA</p>
              <p className=' text-gray-800 py-1 font-Mono font-bold'>SWIFT</p>
              <p className=' text-gray-800 py-1 font-Mono font-bold'>PHP</p>
              <p className=' text-gray-800 py-1 font-Mono font-bold'>JAVASCRIPT</p>
              <p className=' text-gray-800 py-1 font-Mono font-bold'>COTLIN</p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 card'>
              < Image className=' m-auto' src={consulting} alt={'design'} width={100} height={100} />
              <h3 className=' font-lg pt-8 pb-2 font-bold'>Consulting</h3>
              <p>
                Creating elegant design suited for your needs.
              </p>
              <h4 className=' py-4 text-teal-600 font-bold'> Design tools I use</h4>
              <p className=' text-gray-800 py-1'>Photoshop</p>
              <p className=' text-gray-800 py-1'>Kdenlive</p>
              <p className=' text-gray-800 py-1'>GIMP</p>
              <p className=' text-gray-800 py-1'>Blender</p>
              <p className=' text-gray-800 py-1'>Figma</p>
              <p className=' text-gray-800 py-1'>Illustrator</p>
            </div>
          </div>
        </section>
      </main>


    </div>
  )
}
